### ISSUE TITLE
Automated Security Testing and Linting Workflow

### ISSUE THREAD

**Issue by hitchhooker** [rotkonetworks/webjmail#6]
/claude

**Issue**: No automated security checks
**Line**: .github/workflows/
**Attack**: Vulnerabilities slip through code review
**Fix**: Implement comprehensive CI/CD security pipeline

### Required GitHub Actions Workflow:

```yaml
name: Security Pipeline
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'bun'

      - name: Install dependencies
        run: |
          npm install -g bun
          bun install --frozen-lockfile

      - name: Type checking
        run: bun run type-check

      - name: ESLint security rules
        run: |
          bun add -d eslint-plugin-security eslint-plugin-no-unsanitized
          echo "module.exports = {
            extends: ['plugin:security/recommended'],
            plugins: ['security', 'no-unsanitized'],
            rules: {
              'security/detect-object-injection': 'error',
              'security/detect-non-literal-regexp': 'error',
              'security/detect-unsafe-regex': 'error',
              'no-unsanitized/method': 'error',
              'no-unsanitized/property': 'error'
            }
          }" > .eslintrc.security.js
          bun eslint src --ext ts,tsx --config .eslintrc.security.js

      - name: Dependency audit
        run: |
          bun audit
          bunx audit-ci --high

      - name: SAST with Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: |
            - p/security-audit
            - p/typescript
            - p/react
            - p/xss

      - name: Secret scanning
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha }}
          head: HEAD

      - name: License check
        run: bunx license-checker --onlyAllow 'MIT;Apache-2.0;BSD-3-Clause;ISC'

      - name: Bundle size check
        run: |
          bun run build
          bunx size-limit --limit "500 KB"

      - name: OWASP dependency check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'webjmail'
          path: '.'
          format: 'HTML'
          args: >
            --enableRetired
            --enableExperimental

      - name: Coverage with security focus
        run: |
          bun test --coverage --coverageReporters=lcov
          bunx nyc report --reporter=text-lcov > coverage.lcov

      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript,typescript
          queries: security-and-quality

      - name: Build
        run: |
          npm install -g bun
          bun install
          bun run build

      - name: CodeQL analysis
        uses: github/codeql-action/analyze@v3

  docker-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t webjmail:scan .

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'webjmail:scan'
          format: 'sarif'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'

      - name: Grype scan
        uses: anchore/scan-action@v3
        with:
          image: 'webjmail:scan'
          fail-build: true
          severity-cutoff: high

  required-checks:
    needs: [security-scan, codeql, docker-scan]
    runs-on: ubuntu-latest
    steps:
      - name: All security checks passed
        run: echo "✓ Security pipeline complete"
```

### Additional security configs needed:

1. **.semgrep.yml**:
```yaml
rules:
  - id: no-direct-indexeddb-access
    pattern: db.emails.where($X)
    message: Use sync manager for user-isolated queries
    severity: ERROR
    
  - id: no-unsanitized-html
    pattern: dangerouslySetInnerHTML={{__html: $HTML}}
    message: Must use DOMPurify
    severity: ERROR
```

2. **size-limit.json**:
```json
[
  {
    "path": "dist/index.js",
    "limit": "500 KB"
  }
]
```

3. **sonar-project.properties**:
```properties
sonar.projectKey=webjmail
sonar.sources=src
sonar.javascript.lcov.reportPaths=coverage.lcov
sonar.security.hotspots.maxIssues=0
```

This pipeline ensures zero tolerance for security vulnerabilities. Every PR must pass all checks before merge.
